Mappings:
  AmiRegionMap:
    us-east-1:
      AMI: "ami-06ca3ca175f37dd66"
    us-east-2:
      AMI: "ami-069d73f3235b535bd"
    us-west-1:
      AMI: "ami-0fd61683ae1a27a64"
    us-west-2:
      AMI: "ami-0507f77897697c4ba"
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap
         - AmiRegionMap
         - !Ref AWS::Region
         - AMI
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, first, Instance, from, cloudformation]]
      SecurityGroups:
        - !Ref vprofileSG
  vprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from http and ssh to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 192.168.30.178/32