Parameters:
  NameOfService:
    Description: "The name of the service to be used by the stack"
    Type: String
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  KeyName:
    Description: Name of EC2 key value
    Type: AWS::EC2::KeyPair::KeyName
Mappings:
  AmiRegionMap:
    us-east-1:
      AMI: "ami-06ca3ca175f37dd66"
    us-east-2:
      AMI: "ami-069d73f3235b535bd"
    us-west-1:
      AMI: "ami-0fd61683ae1a27a64"
    us-west-2:
      AMI: "ami-0507f77897697c4ba"
Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages: 
            yum:
              httpd: []
              php: []
              wget: []
              unzip: []
              git: []
          commands:
            test:
              command: "wget https://www.tooplate.com/zip-templates/2129_crispy_kitchen.zip && unzip 2129_crispy_kitchen.zip && cp -r 2129_crispy_kitchen/* /var/www/html"
          files:
            /var/www/html/hello.html:
              content: !Sub |
                <!DOCTYPE html>
                <html>
                <body>

                <h1>Welcome to Cloudformation.</h1>
                <p>This site is deployed by Cloudformation</p>

                </body>
                </html>
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref KeyName
      ImageId: !FindInMap
         - AmiRegionMap
         - !Ref AWS::Region
         - AMI
      Tags:
        - Key: "Name"
          Value: !Ref NameOfService
      SecurityGroups:
        - !Ref vprofileSG
      UserData:
       'Fn::Base64':
         !Sub |
             #!/bin/bash -xe            
             # Ensure AWS CFN Bootstrap is the latest
             yum install -y aws-cfn-bootstrap
             # Install the files and packages from the metadata
             /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource WebServer  --region ${AWS::Region}
             /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WebServer  --region ${AWS::Region}
            
  vprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from http and ssh to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 197.210.227.45/32
Outputs:
  PrintSomeInfo:
    Description: a valid printer
    Value: !GetAtt
       - WebServer
       - PublicDnsName